### ISSUE TITLE
Help: Implementing Windows Shell Extension (IThumbnailProvider)

### ISSUE THREAD

**Issue by JackMordaunt** [microsoft/com-rs#140]
I'm attempting to implement [IThumbnailProvider](https://docs.microsoft.com/en-us/windows/win32/shell/thumbnail-providers), but with limited knowledge of Rust FFI and C/C++ interop. 

1. When creating a new COM server, do I need to create a GUID for it? See example:

```rust
// Create GUID (bit of a hack), using `guid` crate for macro.
const CLSID_ICNSPROVIDER: com::IID = com::IID {
    data1: guid! {"1abaf814-4632-41bd-a528-88deac2ff752"}.Data1,
    data2: guid! {"1abaf814-4632-41bd-a528-88deac2ff752"}.Data2,
    data3: guid! {"1abaf814-4632-41bd-a528-88deac2ff752"}.Data3,
    data4: guid! {"1abaf814-4632-41bd-a528-88deac2ff752"}.Data4,
};

// Registration.
inproc_dll_module![(CLSID_ICNSPROVIDER, ICNSProvider),];

// Implement the interface for ICNS icons (MacOS png container).
#[co_class(implements(IThumbnailProvider))]
pub struct ICNSProvider {}

impl ICNSProvider {
    fn new() -> Box<Self> {
        ICNSProvider::allocate()
    }
}
```

2. When defining the interfaces, how do I refer to traits? For example with [`IStream`](https://docs.microsoft.com/en-us/windows/win32/api/objidl/nn-objidl-istream), it refers to itself in the `copy` method: 

```rust 
#[com_interface("0000000c-0000-0000-C000-000000000046")]
pub trait IStream: IUnknown {
    unsafe fn clone(ppstm: dyn IStream) -> HRESULT;
    unsafe fn commit(commit_flags: DWORD) -> HRESULT;
    unsafe fn copy_to(
        ppstm: dyn IStream,
        cb: ULARGE_INTEGER_u,
        pcb_read: *mut ULARGE_INTEGER_u,
        pcb_written: *mut ULARGE_INTEGER_u,
    ) -> HRESULT;
    unsafe fn lock_region(
        lib_offset: ULARGE_INTEGER_u,
        cb: ULARGE_INTEGER_u,
        lock_type: DWORD,
    ) -> HRESULT;
    unsafe fn revert() -> HRESULT;
    unsafe fn seek(
        dlib_move: LARGE_INTEGER,
        dw_origin: DWORD,
        plib_new_position: *mut ULARGE_INTEGER_u,
    ) -> HRESULT;
    unsafe fn set_size(lib_new_size: ULARGE_INTEGER_u) -> HRESULT;
    unsafe fn stat(pstatstg: *mut STATSTG, grf_stat_flag: DWORD) -> HRESULT;
    unsafe fn unlock_region(
        lib_offset: ULARGE_INTEGER_u,
        cb: ULARGE_INTEGER_u,
        lock_type: DWORD,
    ) -> HRESULT;
}
```

I get an error: "TraitObject type unhandled!". This error seems to refer to `unsafe fn clone(ppstm: dyn IStream) -> HRESULT;`.
How am I supposed to reference rust traits in an FFI context? Obviously `dyn IStream` is not valid. 

Thanks!

**Comment by rylev** [comment]
Hi there! 

1.) Yes. COM classes need an CLSID (which is just a guid) associated with them so that the COM registration system knows how to refer to that class. 

2.) `ComPtr<dyn IStream>` is exactly equivalent to a non-null `*mut *mut IStreamVTable` and is safe to send over an FFI boundary (https://github.com/microsoft/com-rs/blob/master/src/ptr.rs#L17) which means on the C++ it should be seen as a `*IStream`.  I would recommend using that. We should definitely create some examples with this.

However, it seems like you're missing`&self` in your interface declarations. Unfortunately C++ has an implicit `this` pointer in all of its methods as the first argument. Rust requires that you explictly state that. So I believe all your methods need a `&self`  with them.

**Comment by Ciantic** [comment]
I also get the same error:
```
custom attribute panicked
message: TraitObject type unhandled!
```

If I try to use the `dyn IMyInterface`:

```rust
#[com_interface("0cd45e71-d927-4f15-8b0a-8fef525337bf")]
pub trait IVirtualDesktopNotificationService: IUnknown {
    unsafe fn register(
        &self,
        notification: dyn IVirtualDesktopNotification, // <-- dyn here
        outCookie: *mut DWORD,
    ) -> HRESULT;

    unsafe fn unregister(&self, cookie: DWORD) -> HRESULT;
}
```

**Comment by Ciantic** [comment]
I see, I need to use `ComPtr<dyn IVirtualDesktopNotification>`... However I've yet to figure out how to create a comptr!

E.g. `ComPtr::from(VirtualDesktopChangeListener::new())` does not work, there needs to be some trick.

More complete examples would be nice.

**Comment by rylev** [comment]
@ciantic Have you made progress on this? The crate has changed significantly since this was reported.

**Comment by Ciantic** [comment]
@rylev I've implemented my behavior already, it's working ( https://github.com/Ciantic/VirtualDesktopAccessor/tree/rust and https://crates.io/crates/winvd ) my comments above was confusion because I didn't know the differences of ComPtr ComDc, and wrapping with Option etc. Though more complete example would help others too.
