### ISSUE TITLE
Using com-rs on a non-windows platform

### ISSUE THREAD

**Issue by stijnfrishert** [microsoft/com-rs#145]
I'd very much like to use the "COM-lite" interface of another C++ library on macOS, but it seems this crate hasn't taken other OS'es into account besides Windows.

Namely, when I try to compile the `IAnimal` interface example given on the documentation landing page, I'm running into linking issues:

```
#[com::com_interface("EFF8970E-C50F-45E0-9284-291CE5A6F771")]
pub trait IAnimal: com::interfaces::IUnknown {
    unsafe fn eat(&self) -> com::sys::HRESULT;
}
```

```
  = note: ld: library not found for -lole32
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error; 1 warning emitted
```

I understand OLE is a big part of COM on Windows, but I'd prefer it if I could use just a subset of this crate that does just vtable generation and interfacing.

**Comment by rylev** [comment]
Hey there! While I wouldn't rule out supporting non-Windows platforms in the future, we're explicitly focusing on COM on Windows for now due to its pervasive use. Hopefully once we reach a good point with Windows support, we can revisit this question. I believe the best alternative to this crate that works on non-Windows platforms is [intercom](https://github.com/Rantanen/intercom) which explicitly supports non-Windows platforms.

**Comment by stijnfrishert** [comment]
Alright, thanks for the recommendation :)
