### ISSUE TITLE
Newbie question about defining interface for a com object

### ISSUE THREAD

**Issue by konghk78** [microsoft/com-rs#152]
Hello, there
First of all, Thanks for your great job.

As a newbie for com technology, I would like to ask few questions about how to use the crate.

1. Defining interface
Should Interface contain all member functions of com server? I tried to define one member of com object, however I always got compile error from macro. 

2. Does camel case matter to define interface when com object provides functions eg.”AbcDef”?

**Comment by rylev** [comment]
Hey 👋. 
1.) ComInterfaces care about the amount and order of their methods because methods are really just offsets into a VTable. That means you must ensure that all methods of parent interfaces are declared _and_ that all methods of the interface in question are declared. Again order matters here. It's important to note that "declaring" methods you're not actually going to use only means you need to have some place holder (e.g., `unsafe fn placeholder0(&self)`). It just matters that the method "slot" is occupied.
2.) Yes our implementation expects "snake_case" and will not work if CamelCase is used. So for a function declared in C++ as `MyFunction` you would declare it in Rust as `my_function`. It should be noted that method names actually don't matter and you can name functions whatever you want (as long as it's snake case). COM only cares about method ordering, and method signatures, not method names.

**Comment by konghk78** [comment]
Thanks a lot for your answers!!
It helps a lot :)
