### ISSUE TITLE
Generation of Class Objects

### ISSUE THREAD

**Issue by adrianwithah** [microsoft/com-rs#32]
As it stands now, users will need to write another struct as the Class Object (BritishShortHairCatClass, etc.) which implements IClassFactory. This class object should be automatically generated, as it has a standard IUnknown implementation as well as deterministic IClassFactory implementation (once we know whether its aggregable/aggregates/normal)

**Comment by Rantanen** [comment]
If generic co_classes (ie. #111) was a suitable approach for this, then the next issue would be the way co_classes are constructed.

Currently they need to expose a `fn new() -> Box<Self>` method, which isn't something that can be used for just `T` in a generic context.

Two approaches I could come up with:
- Add `fn new` in `CoClass`, which is delegated to `Self::new()` when the proc macro implements the `CoClass` trait.
- Instead of having `fn new()` as a "free" function, implement it in a `NewCoClass` trait.
  - This would help in the "not all CoClasses need to be creatable" story (ie. #109)
  - There could be a blanket `impl<T: Default + CoClass> NewCoClass for T { .. }`, which does `Box::new(T::default())` so users can just `#[derive(Default)]` to get `NewCoClass` implemented.

**Comment by rylev** [comment]
This is done.
